pipeline:
  signed-off-check:
    image: nextcloudci/php7.0:php7.0-2
    environment:
    - APP_NAME=circles
    - CORE_BRANCH=shares-circles
    - DB=sqlite
    commands:
      - wget https://raw.githubusercontent.com/nextcloud/travis_ci/master/before_install.sh
      - bash ./before_install.sh $APP_NAME $CORE_BRANCH $DB
      - cd ../server
      - php ./build/signed-off-checker.php
    when:
      matrix:
        TESTS: signed-off-check

  phpunit-test:
    image: nextcloudci/php7.0:php7.0-2
    environment:
    - APP_NAME=circles
    - CORE_BRANCH=shares-circles
    - DB=sqlite
    commands:
    - wget https://raw.githubusercontent.com/nextcloud/travis_ci/master/before_install.sh
    - bash ./before_install.sh $APP_NAME $CORE_BRANCH $DB
    - cd ../server/
    - ./occ app:enable $APP_NAME
    - cd apps/$APP_NAME/tests/

    # phpunit
    - phpunit --configuration phpunit.xml

    # codecov
    - wget https://codecov.io/bash -O codecov.sh
    - bash codecov.sh -B $DRONE_BRANCH -C $DRONE_COMMIT -t ff710fa8-260c-4a61-bdd3-0771d6aea5b5
    when:
      matrix:
        TESTS: phpunit-test



matrix:
  include:
    - TESTS: signed-off-check
    - TESTS: phpunit-test
